main: com.crimsonrpg.personas.personas.PersonasPlugin

name: Personas
description: The Personas plugin for Bukkit.

version: 1.0
author: AlbireoX

commands:
  personas:
    description: Personas base command
    usage: /personas
    
permissions:
  personas.*:
    description: Personas permissions
    default: op
    children:
      personas.reload: true
      personas.save: true
      
  personas.reload:
    description: Enables a player to reload personas.
    
  personas.save:
    description: Enables a player to save personas.